from connect import *

import time

#subroutine/function
def insertFilms():
    films = [] # creating an empty list called films, then look at the fields we have in the database (we dont need to put in a numerical value if its autogenerated)
    # filmID, title, yearReleased, rating, duration, genre

    # filmID is autoincrement and numeric value will be added automatically starting from 1
    #ask for user input
    title = input("Enter Film Title: ")
    yearReleased = int(input("Enter The Year Released: "))
    rating = input("Enter the Film Rating: ")
    duration = int(input("Enter the Film Duration: "))
    genre = input("Enter the Film Genre: ")

    #insert vs append when working with list python?
    # add the data captured from title, yearReleased, rating, duration, genre to the films list
    films.append(title)
    films.append(yearReleased)
    films.append(rating)
    films.append(duration)
    films.append(genre)

    # insert data stored in the list and transfer into the films table (tblFilms) in the database 
    dbCursor.execute("INSERT INTO tblFilms(title, yearReleased, rating, duration, genre) VALUES (?,?,?,?,?)", films)
    dbCon.commit() #save the data permanantly in the table

    print(f"{title} inserted into films table")
if __name__=="__main__": #ensures that when we import a file it does not start executing all the function
    insertFilms()
